name: astar-canvas-demo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  id-token: write
  contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
        
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Pack
        run: wasm-pack build --target web --verbose
          
      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci
        working-directory: www/

      - name: Build frontend
        run: npm run build
        working-directory: www/
        
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            www/dist


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - name: 'az login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - uses: actions/download-artifact@v3
  
    - name: Upload
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} -d '$web' -s ./dist/ --overwrite 
    
    
